name: Docker Image CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  # build and push to docker-hub:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: login to docker hub
  #     uses: docker/login-action@v1
  #     with:
  #         username: ${{ secrets.DOCKER_HUB_USERNAME }}
  #         password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
  #   - name: Set up Docker Buildx
  #     uses: docker/setup-buildx-action@v1
  #     id: buildx
  #   - name: Build and Push
  #     uses: docker/build-push-action@v2
  #     id: docker_build
  #     with:
  #         context: ./
  #         file: ./Dockerfile
  #         push: true
  #         tags: ${{ secrets.DOCKER_HUB_USERNAME }}/figureshop:latest
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd ./
            ls
